name = "travel-capsule-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "R2"
bucket_name = "travel-capsule"

[vars]
SUPABASE_URL = ""
R2_BUCKET_NAME = "travel-capsule"
R2_PUBLIC_URL = ""
POLAR_PRODUCT_ID_STANDARD = ""
POLAR_PRODUCT_ID_PRO = ""
POLAR_PRODUCT_ID_ANNUAL = ""
