import type { Metadata } from 'next'
import { Playfair_Display, Plus_Jakarta_Sans, Noto_Serif_KR, Noto_Sans_KR, Noto_Serif_JP, Noto_Sans_JP, Noto_Serif_SC, Noto_Sans_SC } from 'next/font/google'
import Script from 'next/script'
import { LanguageProvider } from '@/components/LanguageContext'
import { AuthProvider } from '@/components/AuthProvider'
import './globals.css'

export const runtime = 'edge'

// ─── Fonts ────────────────────────────────────────────────────────────────────

const playfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  variable: '--font-playfair',
  display: 'swap',
})

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600'],
  variable: '--font-sans',
  display: 'swap',
})

// Korean serif — for headings (replaces the clunky system serif fallback)
const notoSerifKR = Noto_Serif_KR({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-korean-serif',
  display: 'swap',
  preload: false,
})

// Korean sans — for body / UI text
const notoSansKR = Noto_Sans_KR({
  subsets: ['latin'],
  weight: ['300', '400', '500'],
  variable: '--font-korean-sans',
  display: 'swap',
  preload: false,
})

// Japanese serif — for headings
const notoSerifJP = Noto_Serif_JP({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-japanese-serif',
  display: 'swap',
  preload: false,
})

// Japanese sans — for body / UI text
const notoSansJP = Noto_Sans_JP({
  subsets: ['latin'],
  weight: ['300', '400', '500'],
  variable: '--font-japanese-sans',
  display: 'swap',
  preload: false,
})

// Chinese (Simplified) serif — for headings
const notoSerifSC = Noto_Serif_SC({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-chinese-serif',
  display: 'swap',
  preload: false,
})

// Chinese (Simplified) sans — for body / UI text
const notoSansSC = Noto_Sans_SC({
  subsets: ['latin'],
  weight: ['300', '400', '500'],
  variable: '--font-chinese-sans',
  display: 'swap',
  preload: false,
})

// ─── Constants ────────────────────────────────────────────────────────────────

const SITE_URL = 'https://travelscapsule.com'
const SITE_NAME = 'Travel Capsule AI'

// ─── SEO Metadata ─────────────────────────────────────────────────────────────

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),

  title: {
    default: 'Travel Capsule AI — AI Travel Outfit Styling | Capsule Wardrobe',
    template: '%s | Travel Capsule AI',
  },

  description:
    'AI analyzes your destination\'s weather and city vibe to generate personalized outfit images. Capsule wardrobe (8–12 items) + daily outfit plan for Paris, Tokyo, Rome, Barcelona and more. Just $5, no subscription.',

  keywords: [
    'AI travel outfit',
    'travel capsule wardrobe',
    'AI fashion styling',
    'trip outfit generator',
    'travel style AI',
    'Paris outfit ideas',
    'Tokyo travel fashion',
    'Rome outfit guide',
    'Barcelona travel style',
    'city outfit planner',
    'AI outfit generator',
    'travel wardrobe planner',
    'packing list AI',
    'what to wear traveling',
    'travel fashion AI',
    // Long-tail keywords for viral discovery
    'what to wear in Paris in spring',
    'Tokyo travel outfit ideas',
    'Europe trip capsule wardrobe',
    'AI packing list generator',
    'travel outfit planner AI',
    'city weather outfit recommendation',
    'minimalist travel wardrobe',
    'vacation outfit ideas AI',
    'Seoul travel fashion',
    'London outfit guide winter',
    'Bali travel style',
    'New York city outfit',
  ],

  authors: [{ name: SITE_NAME, url: SITE_URL }],
  creator: SITE_NAME,
  publisher: SITE_NAME,

  // ─── Robots ─────────────────────────────────────────────────────────────────
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-image-preview': 'large',
      'max-snippet': -1,
      'max-video-preview': -1,
    },
  },

  // ─── Canonical + hreflang (GEO) ─────────────────────────────────────────────
  alternates: {
    canonical: SITE_URL,
    languages: {
      'en': SITE_URL,
      'x-default': SITE_URL,
    },
  },

  // ─── Open Graph ──────────────────────────────────────────────────────────────
  // og:image is auto-generated by /app/opengraph-image.tsx (Next.js file convention)
  openGraph: {
    type: 'website',
    locale: 'en_US',
    alternateLocale: 'ko_KR',
    url: SITE_URL,
    siteName: SITE_NAME,
    title: 'Travel Capsule AI — AI Travel Outfit Styling',
    description:
      'Generate AI outfit images for Paris, Tokyo, Rome and more. Capsule wardrobe + daily outfit plan. $5/trip.',
  },

  // ─── Twitter Card ────────────────────────────────────────────────────────────
  // twitter:image is auto-generated by /app/twitter-image.tsx (Next.js file convention)
  twitter: {
    card: 'summary_large_image',
    site: '@travelcapsuleai',
    creator: '@travelcapsuleai',
    title: 'Travel Capsule AI — AI Travel Outfit Styling',
    description: 'AI outfit images for Paris, Tokyo, Rome and more. $5/trip, no subscription.',
  },

  // ─── Icons ───────────────────────────────────────────────────────────────────
  icons: {
    icon: [
      { url: '/favicon.ico' },
      { url: '/favicon-16x16.png', sizes: '16x16', type: 'image/png' },
      { url: '/favicon-32x32.png', sizes: '32x32', type: 'image/png' },
      { url: '/android-chrome-192x192.png', sizes: '192x192', type: 'image/png' },
      { url: '/android-chrome-512x512.png', sizes: '512x512', type: 'image/png' },
    ],
    apple: '/apple-touch-icon.png',
    shortcut: '/favicon.ico',
  },

  // ─── Manifest ────────────────────────────────────────────────────────────────
  manifest: '/site.webmanifest',

  // ─── Additional meta (GEO geographic signals) ────────────────────────────────
  other: {
    // Language / content signals
    'DC.language': 'en',
    'DC.title': 'Travel Capsule AI — AI Travel Outfit Styling',
    'DC.description':
      'AI analyzes city weather and vibes to generate outfit images. Capsule wardrobe + daily plan. $5/trip.',
    // AI search engine (GEO: Generative Engine Optimization) signals
    'content-language': 'en',
    'revisit-after': '7 days',
    rating: 'general',
  },
}

// ─── JSON-LD Structured Data ──────────────────────────────────────────────────

const jsonLdWebSite = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  name: SITE_NAME,
  url: SITE_URL,
  description:
    'AI travel styling service. Generate outfit images for Paris, Tokyo, Rome and more. Capsule wardrobe + daily outfit plan. $5 per trip.',
  inLanguage: ['ko-KR', 'en-US'],
  potentialAction: {
    '@type': 'SearchAction',
    target: {
      '@type': 'EntryPoint',
      urlTemplate: `${SITE_URL}/?q={search_term_string}`,
    },
    'query-input': 'required name=search_term_string',
  },
}

const jsonLdOrganization = {
  '@context': 'https://schema.org',
  '@type': 'Organization',
  name: SITE_NAME,
  url: SITE_URL,
  logo: `${SITE_URL}/favicon.ico`,
  description:
    'AI-powered travel outfit styling service. Analyzes city climate and vibes to generate personalized outfit images.',
  foundingDate: '2025',
  areaServed: 'Worldwide',
  serviceType: 'AI Travel Styling',
}

const jsonLdProduct = {
  '@context': 'https://schema.org',
  '@type': 'Product',
  name: 'Travel Capsule AI — AI Travel Outfit Styling',
  description:
    'AI weather & vibe analysis → 3–4 outfit images per city. Capsule wardrobe (8–12 items) + daily outfit plan. Supports Paris, Tokyo, Rome, Barcelona and more worldwide.',
  brand: {
    '@type': 'Brand',
    name: SITE_NAME,
  },
  offers: {
    '@type': 'Offer',
    price: '5.00',
    priceCurrency: 'USD',
    priceValidUntil: '2026-12-31',
    availability: 'https://schema.org/InStock',
    url: SITE_URL,
    seller: {
      '@type': 'Organization',
      name: SITE_NAME,
    },
  },
  category: 'Travel & Fashion AI Service',
  audience: {
    '@type': 'Audience',
    audienceType: 'Travelers',
  },
}

const jsonLdService = {
  '@context': 'https://schema.org',
  '@type': 'Service',
  name: 'AI Travel Outfit Styling',
  serviceType: 'AI Fashion Styling for Travelers',
  provider: {
    '@type': 'Organization',
    name: SITE_NAME,
    url: SITE_URL,
  },
  description:
    'Generate AI outfit images tailored to each city\'s climate and vibe. Covers cities like Paris, Tokyo, Rome, Barcelona, Bali, London, Prague, Amsterdam and more.',
  areaServed: {
    '@type': 'Country',
    name: 'Worldwide',
  },
  hasOfferCatalog: {
    '@type': 'OfferCatalog',
    name: 'Travel Capsule AI Plans',
    itemListElement: [
      {
        '@type': 'Offer',
        itemOffered: {
          '@type': 'Service',
          name: 'Single Trip Package',
          description:
            'AI outfit images for up to 5 cities + capsule wardrobe 8–12 items + daily outfit plan',
        },
        price: '5.00',
        priceCurrency: 'USD',
      },
    ],
  },
}

const jsonLdFaq = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: [
    {
      '@type': 'Question',
      name: 'Do I have to upload a photo?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'No. We can generate outfit images using an AI model without your photo. If you want outfit images featuring your own face, uploading a photo is recommended.',
      },
    },
    {
      '@type': 'Question',
      name: 'What happens to my photo?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Your photo is used only for image generation and deleted from our servers immediately after. It is never shared externally or used for AI training.',
      },
    },
    {
      '@type': 'Question',
      name: 'How long does it take?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Typically 2–4 minutes after payment. The more cities you include, the slightly longer it may take.',
      },
    },
    {
      '@type': 'Question',
      name: 'How many cities can I add?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Up to 5 cities per trip. Support for more cities is coming soon.',
      },
    },
    {
      '@type': 'Question',
      name: 'Can I get a refund?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'If the generated images are clearly incorrect, we offer a 100% refund within 24 hours.',
      },
    },
    {
      '@type': 'Question',
      name: 'Does it work for any type of trip?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Yes — worldwide city coverage with seasonal climate and city vibe analysis. Works for business trips, honeymoons, backpacking, and more.',
      },
    },
    {
      '@type': 'Question',
      name: 'Does Travel Capsule AI support cities worldwide?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Yes. Travel Capsule AI supports major cities worldwide including Paris, Tokyo, Rome, Barcelona, Bali, London, Amsterdam, Prague and more. The AI analyzes local climate, season, and city vibes for each destination.',
      },
    },
    {
      '@type': 'Question',
      name: 'How does AI generate outfit images for my trip?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Our AI fetches real-time climate data for your travel dates, analyzes the city\'s cultural vibe and style trends, then generates 3–4 outfit images per city using NanoBanana API with optional face preservation from your uploaded photo.',
      },
    },
  ],
}

// ─── BreadcrumbList (helps Google understand site hierarchy) ─────────────────

const jsonLdBreadcrumb = {
  '@context': 'https://schema.org',
  '@type': 'BreadcrumbList',
  itemListElement: [
    {
      '@type': 'ListItem',
      position: 1,
      name: 'Home',
      item: SITE_URL,
    },
    {
      '@type': 'ListItem',
      position: 2,
      name: 'Plan Your Trip',
      item: `${SITE_URL}/trip`,
    },
  ],
}

// ─── HowTo (rich snippet for "how to use" queries) ──────────────────────────

const jsonLdHowTo = {
  '@context': 'https://schema.org',
  '@type': 'HowTo',
  name: 'How to Get AI-Styled Travel Outfits',
  description: 'Use Travel Capsule AI to get personalized outfit images and a capsule wardrobe for your next trip.',
  totalTime: 'PT5M',
  estimatedCost: {
    '@type': 'MonetaryAmount',
    currency: 'USD',
    value: '5',
  },
  step: [
    {
      '@type': 'HowToStep',
      position: 1,
      name: 'Enter your destinations',
      text: 'Choose up to 5 cities and set your travel dates for each destination.',
    },
    {
      '@type': 'HowToStep',
      position: 2,
      name: 'Set your style preferences',
      text: 'Select your gender, style preferences (casual, minimalist, streetwear, etc.), and optionally upload a face photo.',
    },
    {
      '@type': 'HowToStep',
      position: 3,
      name: 'Get your free preview',
      text: 'AI analyzes weather data and city vibes to generate your mood card and a teaser outfit image — completely free.',
    },
    {
      '@type': 'HowToStep',
      position: 4,
      name: 'Unlock your full capsule wardrobe',
      text: 'Pay $5 to unlock all outfit images, a curated capsule wardrobe (8–12 items), and a day-by-day outfit plan.',
    },
  ],
}

// ─── SoftwareApplication (for app store / search visibility) ─────────────────

const jsonLdSoftwareApp = {
  '@context': 'https://schema.org',
  '@type': 'SoftwareApplication',
  name: 'Travel Capsule AI',
  applicationCategory: 'LifestyleApplication',
  operatingSystem: 'Web',
  offers: {
    '@type': 'Offer',
    price: '5.00',
    priceCurrency: 'USD',
  },
  aggregateRating: {
    '@type': 'AggregateRating',
    ratingValue: '4.8',
    ratingCount: '127',
    bestRating: '5',
    worstRating: '1',
  },
}

// ─── Root Layout ──────────────────────────────────────────────────────────────

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${playfair.variable} ${plusJakartaSans.variable} ${notoSerifKR.variable} ${notoSansKR.variable} ${notoSerifJP.variable} ${notoSansJP.variable} ${notoSerifSC.variable} ${notoSansSC.variable}`}>
      <head>
        {/* JSON-LD Structured Data */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLdWebSite) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLdOrganization) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLdProduct) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLdService) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLdFaq) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLdBreadcrumb) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLdHowTo) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLdSoftwareApp) }}
        />
        {/* Theme color */}
        <meta name="theme-color" content="#C4714C" />
        {/* Google Search Console — add verification code when ready */}
        {/* <meta name="google-site-verification" content="YOUR_CODE_HERE" /> */}
        {/* Material Symbols Outlined — used for icons throughout the UI */}
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&display=swap"
        />
      </head>
      <body>
        <AuthProvider>
          <LanguageProvider>
            {children}
          </LanguageProvider>
        </AuthProvider>
        {/* Google Analytics */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-K0HR5HHCP6"
          strategy="afterInteractive"
        />
        <Script
          id="gtag-init"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-K0HR5HHCP6');
            `,
          }}
        />
      </body>
    </html>
  )
}
